@host = https://localhost
@port = 7042

@Restaurants.API_HostAddress = https://localhost:7042

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/
Accept: application/json
ProjectUrl: {{$projectUrl}}
Guid: {{$guid}}
LocalDate: {{$datetime iso8601}} 
Random-int: {{$randomInt}}

###


POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?count=10
Content-Type: application/json

{
  "min":-22,5,
   "max": 44
}

###
